### Test NormalizeSound endpoint with valid request
# @no-log

POST {{HostAddress}}/api/NormalizeSound?code={{code}}
Content-Type: application/json

{
  "soundUrl": "https://static.ordnet.dk/mp3/12004/12004770_1.mp3",
  "word": "underholdning",
  "version": "1"
}

> {%

  // Assert status code and content type
  client.test('When sending a valid sound URL, we expect to get 200 (OK)', () => {
    client.assert(response.status === 200, "Response status is 200");
  });

  client.test('Response should be audio/mpeg', () => {
    client.assert(response.contentType.mimeType === "audio/mpeg", "Content-Type is audio/mpeg");
  });

  client.test('Response should have content', () => {
    client.assert(response.body.length > 0, "Response body has content");
  });
%}

### Test NormalizeSound endpoint with empty soundUrl (should return BadRequest)

POST {{HostAddress}}/api/NormalizeSound?code={{code}}
Content-Type: application/json

{
  "soundUrl": "",
  "word": "test",
  "version": "1"
}

> {%

  // Assert status code
  client.test('When soundUrl is empty, we expect to get BadRequest', () => {
    client.assert(response.status === 400, "Response status is 400");
  });
%}


### Test NormalizeSound endpoint with null body (should return BadRequest)

POST {{HostAddress}}/api/NormalizeSound?code={{code}}
Content-Type: application/json

> {%

  // Assert status code
  client.test('When request body is null, we expect to get BadRequest', () => {
    client.assert(response.status === 400, "Response status is 400");
  });
%}

### Test NormalizeSound endpoint with unsupported protocol version (should return BadRequest)

POST {{HostAddress}}/api/NormalizeSound?code={{code}}
Content-Type: application/json

{
  "soundUrl": "https://example.com/audio/sample.mp3",
  "word": "example",
  "version": "2"
}

> {%

  // Assert status code
  client.test('When version is not "1", we expect to get BadRequest', () => {
    client.assert(response.status === 400, "Response status is 400");
  });
%}

### Test NormalizeSound endpoint with invalid code (should return Unauthorized)

POST {{HostAddress}}/api/NormalizeSound?code=wrong-code
Content-Type: application/json

{
  "soundUrl": "https://example.com/audio/sample.mp3",
  "word": "example",
  "version": "1"
}

> {%

  // Assert status code
  client.test('When code is invalid, we expect to get Unauthorized', () => {
    client.assert(response.status === 401, "Response status is 401");
  });
%}