### Suggested words for Danish "isstang"

POST {{HostAddress}}/api/v2/Translation/SuggestedWords?code={{code}}
Content-Type: application/json

{
    "Text": "isstang",
    "SourceLanguage": "Danish",
    "DestinationLanguage": "Russian",
    "ActiveDictionaries": ["Danish"],
    "Version": "2"
}

> {%

  client.test('When requesting Danish suggested words for isstang, we expect DDO suggestions', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(Array.isArray(response.body.words), "words is an array");
    client.assert(response.body.words.length > 0, "words has at least one suggestion");
    client.assert(response.body.words.includes("stang"), "contains 'lygte'");
    client.assert(response.body.words.includes("isslag"), "contains 'flygte'");
  });
%}
