### Suggested words for "xyz"

POST {{HostAddress}}/api/v2/Translation/SuggestedWords?code={{code}}
Content-Type: application/json

{
    "Text": "xyz",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  client.test('When requesting suggested words, we expect a list in words property', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(Array.isArray(response.body.words), "words is an array");
    client.assert(response.body.words.length === 5, "words has 5 suggestions");
    client.assert(response.body.words[0] === "xylophone");
    client.assert(response.body.words[1] === "xylocopa");
    client.assert(response.body.words[2] === "xylograph");
    client.assert(response.body.words[3] === "xylography");
    client.assert(response.body.words[4] === "xyster");
  });
%}

### Suggested words for Spanish "hacer estiramientos"

POST {{HostAddress}}/api/v2/Translation/SuggestedWords?code={{code}}
Content-Type: application/json

{
    "Text": "hacer estiramientos",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  client.test('When requesting Spanish suggested words for hacer estiramientos, we expect SpanishDict suggestions', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(Array.isArray(response.body.words), "words is an array");
    client.assert(response.body.words.length > 0, "words has at least one suggestion");
    client.assert(response.body.words.includes("hacer esto"), "contains 'hacer esto'");
  });
%}

### Suggested words - Unauthorized when code is invalid

POST {{HostAddress}}/api/v2/Translation/SuggestedWords?code=invalid-code
Content-Type: application/json

{
    "Text": "xyz",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  client.test('When code is invalid, we expect unauthorized', () => {
    client.assert(response.status === 401, "Response status is 401");
  });
%}

### Suggested words - BadRequest for invalid payload

POST {{HostAddress}}/api/v2/Translation/SuggestedWords?code={{code}}
Content-Type: application/json

{
    "Text": "xyz",
    "SourceLanguage": null,
    "DestinationLanguage": null,
    "Version": "2"
}

> {%

  client.test('When required fields are null, we expect bad request', () => {
    client.assert(response.status === 400, "Response status is 400");
  });
%}
