### Translate "afeitar" from Spanish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "afeitar",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");

    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);
    client.assert(response.body.definition.contexts[0].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[0].meanings[0]["lookupUrl"].length > 0);
  });
%}

### Translate "coche" from Spanish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "coche",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");

    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);

    client.assert(response.body.definition.contexts[0].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[1].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[2].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[3].meanings[0]["translation"].length > 0);

    client.assert(response.body.definition.contexts[0].meanings[0]["lookupUrl"].length > 0);
  });
%}

### Translate "coche" from Spanish to Danish

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "coche",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Danish",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");

    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);

    client.assert(response.body.definition.contexts[0].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[1].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[2].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[3].meanings[0]["translation"].length > 0);
  });
%}

### Translate "wasapear" from Spanish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "wasapear",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");

    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);

    client.assert(response.body.definition.contexts[0].meanings[0]["translation"].length > 0);
  });
%}

### Look up "xyz" in the Spanish dictionary - expect to get Not Found

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "xyz",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 404, "Response status is 404");
  });
%}

### Look up "fine-tooth comb" in the Spanish dictionary - expect to get Not Found

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "https://www.spanishdict.com/translate/fine-tooth%20comb?langFrom=en",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 404, "Response status is 404");
  });
%}

### Look up Danish text with only Spanish active dictionary - expect to get Not Found

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "stå af",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "ActiveDictionaries": ["Spanish"],
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When Danish text is sent with only Spanish active dictionary, we expect not found', () => {
    client.assert(response.status === 404, "Response status is 404");
  });
%}

### BadRequest - Several required fields are null

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "coche",
    "SourceLanguage": null,
    "DestinationLanguage": null,
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When several required fields are null, we expect to get an error', () => {
    client.assert(response.status === 400, "Response status is BadRequest");
    client.assert(response.body.title === "One or more validation errors occurred.")
  });
%}
