### (Version 2) Translate "såsom" from Danish to English + Russian

POST {{HostAddress}}/api/Translate?code={{code}}
Content-Type: application/json

{
    "Version": "2",
    "SourceLanguage": "Danish",
    "DestinationLanguage": "Russian",
    "Definitions": [
        {
            "id": 1,
            "Headword": {
                "Text": "såsom",
                "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
                "PartOfSpeech": "konjunktion",
                "Examples": [
                    "Festdragterne blev anvendt til større fester, såsom konfirmationer, bryllupper og dans omkring majstangen"
                ]
            },
            "Contexts": [
                {
                    "id": 1,
                    "Meanings": [
                        {
                            "id": 1,
                            "Text": "bruges til angivelse af et eller flere eksempler på noget",
                            "Examples": [
                                "Festdragterne blev anvendt til større fester, såsom konfirmationer, bryllupper og dans omkring majstangen"
                            ]
                        },
                        {
                            "id": 2,
                            "Text": "bruges som indledning til en ledsætning der angiver en begrundelse",
                            "Examples": [
                                "han .. var sit firmas dygtigste sælger, såsom han flere år i træk havde præsteret de flotteste salgstal"
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.definitions[0]["id"] === 1);
    client.assert(response.body.definitions[0]["headwordTranslation"].length > 0);
    client.assert(response.body.definitions[0]["headwordTranslationEnglish"].length > 0);

    client.assert(response.body.definitions[0].contexts[0]["id"] === 1);

    client.assert(response.body.definitions[0].contexts[0].meanings[0]["id"] === 1);
    client.assert(response.body.definitions[0].contexts[0].meanings[0]["meaningTranslation"].length > 0);

    client.assert(response.body.definitions[0].contexts[0].meanings[1]["id"] === 2);
    client.assert(response.body.definitions[0].contexts[0].meanings[1]["meaningTranslation"].length > 0);
  });
%}

### (Version 2) Translate "afeitar" from Spanish to English + Russian

POST {{HostAddress}}/api/Translate?code={{code}}
Content-Type: application/json

{
    "Version": "2",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Definitions": [
        {
            "id": 1,
            "PartOfSpeech": "transitive verb",
            "Headword": {
                "Text": "afeitar",
                "Meaning": "to shave (to remove hair)",
                "Examples": [
                    "Para el verano, papá decidió afeitar al perro."
                ]
            },
            "Contexts": [
                {
                    "id": 1,
                    "Meanings": [
                        {
                            "id": 1,
                            "Text": "to shave (to remove hair)",
                            "Examples": [
                                "Para el verano, papá decidió afeitar al perro."
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "id": 2,
            "PartOfSpeech": "transitive verb",
            "Headword": {
                "Text": "afeitarse",
                "Meaning": "to shave (to shave oneself)",
                "Examples": [
                    "¿Con qué frecuencia te afeitas la barba?"
                ]
            },
            "Contexts": [
                {
                    "id": 1,
                    "Meanings": [
                        {
                            "id": 1,
                            "Text": "to shave (to shave oneself)",
                            "Examples": [
                                "¿Con qué frecuencia te afeitas la barba?"
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");

    client.assert(response.body.definitions[0]["id"] === 1);
    client.assert(response.body.definitions[0]["headwordTranslation"].length > 0);
    client.assert(response.body.definitions[0]["headwordTranslationEnglish"].length > 0);

    client.assert(response.body.definitions[0].contexts[0]["id"] === 1);
    client.assert(response.body.definitions[0].contexts[0].meanings[0]["id"] === 1);
    client.assert(response.body.definitions[0].contexts[0].meanings[0]["meaningTranslation"].length > 0);

    client.assert(response.body.definitions[1]["id"] === 2);
    client.assert(response.body.definitions[1]["headwordTranslation"].length > 0);
    client.assert(response.body.definitions[1]["headwordTranslationEnglish"].length > 0);

    client.assert(response.body.definitions[1].contexts[0]["id"] === 1);
    client.assert(response.body.definitions[1].contexts[0].meanings[0]["id"] === 1);
    client.assert(response.body.definitions[1].contexts[0].meanings[0]["meaningTranslation"].length > 0);
  });
%}


### (Version 2) Translate "coche" from Spanish to English + Russian

POST {{HostAddress}}/api/Translate?code={{code}}
Content-Type: application/json

{
    "Version": "2",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Definitions": [
        {
            "id": 1,
            "PartOfSpeech": "masculine noun",
            "Headword": {
                "Text": "el coche",
                "Meaning": "car",
                "Examples": [
                    "Mi coche no prende porque tiene una falla en el motor."
                ]
            },
            "Contexts": [
                {
                    "id": 1,
                    "ContextString": "(vehicle)",
                    "Meanings": [
                        {
                            "id": 1,
                            "Text": "car",
                            "Examples": [
                                "Mi coche no prende porque tiene una falla en el motor."
                            ]
                        }
                    ]
                },
                {
                    "id": 2,
                    "ContextString": "(vehicle led by horses)",
                    "Meanings": [
                        {
                            "id": 1,
                            "Text": "carriage",
                            "Examples": [
                                "Los monarcas llegaron en un coche elegante."
                            ]
                        }
                    ]
                },
                {
                    "id": 3,
                    "ContextString": "(train car)",
                    "Meanings": [
                        {
                            "id": 1,
                            "Text": "car",
                            "Examples": [
                                "Tu mamá y yo vamos a pasar al coche comedor para almorzar."
                            ]
                        }
                    ]
                },
                {
                    "id": 4,
                    "ContextString": "(for babies)",
                    "Meanings": [
                        {
                            "id": 1,
                            "Text": "stroller",
                            "Examples": [
                                "La niñita no se quería subir al coche. Quería ir caminando."
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");

    client.assert(response.body.definitions[0]["id"] === 1);
    client.assert(response.body.definitions[0]["headwordTranslation"].length > 0);
    client.assert(response.body.definitions[0]["headwordTranslationEnglish"].length > 0);

    client.assert(response.body.definitions[0].contexts[0]["id"] === 1);
    client.assert(response.body.definitions[0].contexts[0].meanings[0]["id"] === 1);
    client.assert(response.body.definitions[0].contexts[0].meanings[0]["meaningTranslation"].length > 0);

    client.assert(response.body.definitions[0].contexts[1]["id"] === 2);
    client.assert(response.body.definitions[0].contexts[1].meanings[0]["id"] === 1);
    client.assert(response.body.definitions[0].contexts[1].meanings[0]["meaningTranslation"].length > 0);

    client.assert(response.body.definitions[0].contexts[2]["id"] === 3);
    client.assert(response.body.definitions[0].contexts[2].meanings[0]["id"] === 1);
    client.assert(response.body.definitions[0].contexts[2].meanings[0]["meaningTranslation"].length > 0);

    client.assert(response.body.definitions[0].contexts[3]["id"] === 4);
    client.assert(response.body.definitions[0].contexts[3].meanings[0]["id"] === 1);
    client.assert(response.body.definitions[0].contexts[3].meanings[0]["meaningTranslation"].length > 0);
  });
%}



### (Version 2) BadRequest - Several required fields are null

POST {{HostAddress}}/api/Translate?code={{code}}
Content-Type: application/json

{
  "Version": "2",
  "SourceLanguage": null,
  "DestinationLanguage": null,
  "Definitions": [
    {
      "Headword": null,
      "Meanings": null
    }
  ]
}

> {%

  // Assert status code
  client.test('When several required fields are null, we expect to get an error', () => {
    client.assert(response.status === 400, "Response status is BadRequest");
    client.assert(response.body.title === "One or more validation errors occurred.")
  });
%}