### AI suggestions from Russian to Danish

POST {{HostAddress}}/api/v3/Translation/SuggestedWords?code={{code}}
Content-Type: application/json

{
    "Text": "привет",
    "DestinationLanguage": "Danish"
}

> {%
  client.test('When requesting Russian suggestions, we expect AI suggestions', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(Array.isArray(response.body.words), "words is an array");
  });
%}
