### Translate "såsom" from Danish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "såsom",
    "SourceLanguage": "Danish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);

    client.assert(response.body.definition.contexts[0].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[0].meanings[1]["translation"].length > 0);
  });
%}

### Translate a variant for "bestemt" from Danish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "https://ordnet.dk/ddo/ordbog?select=bestemme&query=bestemt",
    "SourceLanguage": "Danish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);

    client.assert(response.body.definition.contexts[0].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[0].meanings[1]["translation"].length > 0);
  });
%}

### Translate a variant for "ramme" from Danish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "https://ordnet.dk/ddo/ordbog?select=ramme,3&query=rammer",
    "SourceLanguage": "Danish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["partOfSpeech"] === "verbum");

    client.assert(response.body.definition["headword"]["translation"].length > 0);

    client.assert(response.body.definition.contexts[0].meanings[0]["translation"].length > 0);
  });
%}

### Translate "skyldes" from Danish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "skyldes",
    "SourceLanguage": "Danish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);

    client.assert(response.body.definition.contexts[0].meanings[0]["translation"].length > 0);
  });
%}

### Translate "slå" from Danish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "slå",
    "SourceLanguage": "Danish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);

    client.assert(response.body.variants[0]["url"] === "https://ordnet.dk/ddo/ordbog?select=sl%C3%A5,1&query=sl%C3%A5");
    client.assert(response.body.variants[1]["url"] === "https://ordnet.dk/ddo/ordbog?select=sl%C3%A5,2&query=sl%C3%A5");
    client.assert(response.body.variants[2]["url"] === "https://ordnet.dk/ddo/ordbog?select=sl%C3%A5%20om-nederdel&query=sl%C3%A5");

    client.assert(response.body.expressions[0]["url"] === "https://ordnet.dk/ddo/ordbog?mselect=59006368&query=sl%C3%A5");
  });
%}

### Translate a variant for "slå" from Danish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "https://ordnet.dk/ddo/ordbog?select=sl%C3%A5%20om-nederdel&query=sl%C3%A5",
    "SourceLanguage": "Danish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.definition["headword"]["original"] === "slå om-nederdel");
    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);
  });
%}


### Translate "at ligge" (a verb with 'at') from Danish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "at ligge",
    "SourceLanguage": "Danish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);
  });
%}

### Translate "snabel-a" (check encoding of the search query parameter) from Danish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "snabel-a",
    "SourceLanguage": "Danish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);
  });
%}

### Translate "afeitar" from Spanish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "afeitar",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");

    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);
    client.assert(response.body.definition.contexts[0].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[0].meanings[0]["lookupUrl"].length > 0);
  });
%}


### Translate "coche" from Spanish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "coche",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");

    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);

    client.assert(response.body.definition.contexts[0].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[1].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[2].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[3].meanings[0]["translation"].length > 0);

    client.assert(response.body.definition.contexts[0].meanings[0]["lookupUrl"].length > 0);
  });
%}


### Translate "coche" from Spanish to Danish

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "coche",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Danish",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");

    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);

    client.assert(response.body.definition.contexts[0].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[1].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[2].meanings[0]["translation"].length > 0);
    client.assert(response.body.definition.contexts[3].meanings[0]["translation"].length > 0);
  });
%}

### Translate "wasapear" from Spanish to Russian

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "wasapear",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");

    client.assert(response.body.definition["headword"]["english"].length > 0);
    client.assert(response.body.definition["headword"]["translation"].length > 0);

    client.assert(response.body.definition.contexts[0].meanings[0]["translation"].length > 0);
  });
%}

### Look up "xyz" in the Spanish dictionary - expect to get Not Found

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "xyz",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 404, "Response status is 404");
  });
%}

### Look up "fine-tooth comb" in the Spanish dictionary - expect to get Not Found

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "https://www.spanishdict.com/translate/fine-tooth%20comb?langFrom=en",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 404, "Response status is 404");
  });
%}


### BadRequest - Several required fields are null

POST {{HostAddress}}/api/v2/Translation/LookUpWord?code={{code}}
Content-Type: application/json

{
    "Text": "coche",
    "SourceLanguage": null,
    "DestinationLanguage": null,
    "Version": "2"
}

> {%

  // Assert status code
  client.test('When several required fields are null, we expect to get an error', () => {
    client.assert(response.status === 400, "Response status is BadRequest");
    client.assert(response.body.title === "One or more validation errors occurred.")
  });
%}

### Suggested words for "xyz"

POST {{HostAddress}}/api/v2/Translation/SuggestedWords?code={{code}}
Content-Type: application/json

{
    "Text": "xyz",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  client.test('When requesting suggested words, we expect a list in words property', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.words.length === 10);
    client.assert(response.body.words[0] === "xyz 1");
  });
%}

### Suggested words for Danish "islygte"

POST {{HostAddress}}/api/v2/Translation/SuggestedWords?code={{code}}
Content-Type: application/json

{
    "Text": "islygte",
    "SourceLanguage": "Danish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  client.test('When requesting Danish suggested words for islygte, we expect DDO suggestions', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(Array.isArray(response.body.words), "words is an array");
    client.assert(response.body.words.length > 0, "words has at least one suggestion");
    client.assert(response.body.words.includes("lygte"), "contains 'lygte'");
    client.assert(response.body.words.includes("flygte"), "contains 'flygte'");
  });
%}

### Suggested words for Spanish "hacer estiramientos"

POST {{HostAddress}}/api/v2/Translation/SuggestedWords?code={{code}}
Content-Type: application/json

{
    "Text": "hacer estiramientos",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  client.test('When requesting Spanish suggested words for hacer estiramientos, we expect SpanishDict suggestions', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(Array.isArray(response.body.words), "words is an array");
    client.assert(response.body.words.length > 0, "words has at least one suggestion");
    client.assert(response.body.words.includes("hacer esto"), "contains 'hacer esto'");
  });
%}

### Suggested words for Russian "привет"

POST {{HostAddress}}/api/v2/Translation/SuggestedWords?code={{code}}
Content-Type: application/json

{
    "Text": "привет",
    "SourceLanguage": "Danish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  client.test('When requesting Russian suggested words, we expect stub Russian suggestions', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(Array.isArray(response.body.words), "words is an array");
    client.assert(response.body.words.length === 10, "words has 10 suggestions");
    client.assert(response.body.words[0] === "привет1");
    client.assert(response.body.words[9] === "привет10");
  });
%}

### Suggested words - Unauthorized when code is invalid

POST {{HostAddress}}/api/v2/Translation/SuggestedWords?code=invalid-code
Content-Type: application/json

{
    "Text": "xyz",
    "SourceLanguage": "Spanish",
    "DestinationLanguage": "Russian",
    "Version": "2"
}

> {%

  client.test('When code is invalid, we expect unauthorized', () => {
    client.assert(response.status === 401, "Response status is 401");
  });
%}

### Suggested words - BadRequest for invalid payload

POST {{HostAddress}}/api/v2/Translation/SuggestedWords?code={{code}}
Content-Type: application/json

{
    "Text": "xyz",
    "SourceLanguage": null,
    "DestinationLanguage": null,
    "Version": "2"
}

> {%

  client.test('When required fields are null, we expect bad request', () => {
    client.assert(response.status === 400, "Response status is 400");
  });
%}
