stages:
    - stage: Build

      jobs:
          - job: Build

            steps:
                - task: PowerShell@2
                  displayName: 'PowerShell Script - set buld number variable'
                  inputs:
                      targetType: 'inline'
                      script: |
                          Write-Host "##vso[build.updatebuildnumber]$(major).$(minor).$(Build.BuildId)"

                - task: PowerShell@2
                  displayName: 'PowerShell Script - update version number in project files'
                  inputs:
                      targetType: filePath
                      arguments: "-version '$(Build.BuildNumber)'"
                      filePath: './.build/UpdateVersion.ps1'

                - script: yarn install
                  displayName: 'yarn install'

                - script: yarn prettier:check
                  displayName: 'Check prettier adherence'

                - task: UseDotNet@2
                  inputs:
                      version: '9.0.100'

                - task: DotNetCoreCLI@2
                  displayName: 'dotnet test'
                  inputs:
                      command: 'test'
                      projects: '**/*Tests.csproj'
                      arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
                      publishTestResults: true
