trigger:
    branches:
        include:
            - master

pool:
    #vmImage: windows-latest
    #name: windows-private
    name: Default

stages:
    # Build and Lint
    - template: /.azuredevops/templates/build.yml

    # Deploy application to single specific environment
    - template: /.azuredevops/templates/release.yml
