trigger:
    branches:
        include:
            - master

pool:
    vmImage: 'ubuntu-latest'
    #name: windows-private
    #name: Default

variables:
    - group: AccessTokens

stages:
    # Build and run tests. If the source branch is master, also deploy to the container registry.
    - template: /.azuredevops/templates/build.yml

    - template: /.azuredevops/templates/stages-sync-with-github.yaml
      parameters:
          repository: Translations
