#@service=azure
@service=openai

### Translate "såsom" from Danish to English + Russian

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "SourceLanguage": "da",
  "DestinationLanguages": [
    "ru",
    "en"
  ],
  "Word": "såsom",
  "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
  "PartOfSpeech": "konjunktion"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.Translations[0]["Language"] === "ru");
    client.assert(response.body.Translations[0]["TranslationVariants"].length > 0);
    client.assert(response.body.Translations[1]["Language"] === "en");
    client.assert(response.body.Translations[1]["TranslationVariants"].length > 0);
  });
%}


### Translate "støbe" from Danish to English + Russian

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "SourceLanguage": "da",
  "DestinationLanguages": [
    "ru",
    "en"
  ],
  "Word": "støbe",
  "Meaning": "fremstille en genstand ved at lade en flydende masse størkne eller stivne til en bestemt form, ofte i en tildannet støbeform",
  "PartOfSpeech": "verbum",
  "Examples": [
      "kemikalierne, især tungmetaller, skal støbes ind i beton",
      "I denne del af verden er vores moral støbt sammen af de ti bud"
  ]
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.Translations[0]["Language"] === "ru");
    client.assert(response.body.Translations[0]["TranslationVariants"].length > 0);
    client.assert(response.body.Translations[1]["Language"] === "en");
    client.assert(response.body.Translations[1]["TranslationVariants"].length > 0);
  });
%}


### Meaning is null

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "SourceLanguage": "da",
  "DestinationLanguages": [
    "ru",
    "en"
  ],
  "Word": "såsom",
  "Meaning": "",
  "PartOfSpeech": "konjunktion"
}

> {%

  // Assert status code
  client.test('When meaning, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.Translations[0]["Language"] === "ru");
    client.assert(response.body.Translations[0]["TranslationVariants"].length > 0);
    client.assert(response.body.Translations[1]["Language"] === "en");
    client.assert(response.body.Translations[1]["TranslationVariants"].length > 0);
  });
%}



### BadRequest - SourceLanguage is null

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "Word": "såsom",
  "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
  "PartOfSpeech": "konjunktion",
  "SourceLanguage": "",
  "DestinationLanguages": [
    "en",
    "ru"
  ]
}

> {%

  // Assert status code
  client.test('When SourceLanguage is null, we expect to get an error', () => {
    client.assert(response.status === 400, "Response status is BadRequest");
    client.assert(response.body.Error === "Error: 'Source Language' must not be empty.");
  });
%}



### BadRequest - Word is null

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "Word": "",
  "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
  "PartOfSpeech": "konjunktion",
  "SourceLanguage": "Danish",
  "DestinationLanguages": [
    "en",
    "ru"
  ]
}

> {%

  // Assert status code
  client.test('When Word is null, we expect to get an error', () => {
    client.assert(response.status === 400, "Response status is BadRequest");
    client.assert(response.body.Error === "Error: 'Word' must not be empty.");
  });
%}



### BadRequest - DestinationLanguages is null

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "Word": "såsom",
  "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
  "PartOfSpeech": "konjunktion",
  "SourceLanguage": "Danish",
  "DestinationLanguages": null
}

> {%

  // Assert status code
  client.test('When DestinationLanguages is null, we expect to get an error', () => {
    client.assert(response.status === 400, "Response status is BadRequest");
    client.assert(response.body.Error === "Error: 'DestinationLanguages' must have at least one element and fewer than two.");
  });
%}



### BadRequest - DestinationLanguages has too many elements

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "Word": "såsom",
  "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
  "PartOfSpeech": "konjunktion",
  "SourceLanguage": "Danish",
  "DestinationLanguages": [
    "en",
    "ru",
    "es"
  ]
}

> {%

  // Assert status code
  client.test('When DestinationLanguages has too many elements, we expect to get an error', () => {
    client.assert(response.status === 400, "Response status is BadRequest");
    client.assert(response.body.Error === "Error: 'DestinationLanguages' must have at least one element and fewer than two.");
  });
%}


### BadRequest - Several required fielsds are null

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "HeadWord": null,
  "Meaning": null,
  "PartOfSpeech": "konjunktion",
  "SourceLanguage": null,
  "DestinationLanguages": null
}

> {%

  // Assert status code
  client.test('When several required fields are null, we expect to get an error', () => {
    client.assert(response.status === 400, "Response status is BadRequest");
    client.assert(response.body.Error === "Error: 'Source Language' must not be empty, 'DestinationLanguages' must have at least one element and fewer than two, 'Word' must not be empty.");
  });
%}


### Test connection to Azure Translator Service

https://api.cognitive.microsofttranslator.com/languages?api-version=3.0

###
