#@service=azure
@service=openai

### Translate "såsom" from Danish to English + Russian

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "SourceLanguage": "da",
  "DestinationLanguages": [
    "ru",
    "en"
  ],
  "Word": "såsom",
  "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
  "PartOfSpeech": "konjunktion"
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body.Translations[0]["Language"] === "ru");
    client.assert(response.body.Translations[0]["Translation"] !== "");
    client.assert(response.body.Translations[1]["Language"] === "en");
    client.assert(response.body.Translations[1]["Translation"] === "such as");
  });
%}


### Translate "støbe" from Danish to English + Russian

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "SourceLanguage": "da",
  "DestinationLanguages": [
    "ru",
    "en"
  ],
  "Word": "støbe",
  "Meaning": "fremstille en genstand ved at lade en flydende masse størkne eller stivne til en bestemt form, ofte i en tildannet støbeform",
  "PartOfSpeech": "verbum",
  "Examples": [
      "kemikalierne, især tungmetaller, skal støbes ind i beton",
      "I denne del af verden er vores moral støbt sammen af de ti bud"
  ]
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body.Translations[0]["Language"] === "ru");
    client.assert(response.body.Translations[0]["Translation"] !== "");
    client.assert(response.body.Translations[1]["Language"] === "en");
    client.assert(response.body.Translations[1]["Translation"] === "to cast");
  });
%}


### Translate from Danish to English + Russian, where meaning is empty

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "SourceLanguage": "da",
  "DestinationLanguages": [
    "ru",
    "en"
  ],
  "Word": "såsom",
  "Meaning": "",
  "PartOfSpeech": "konjunktion"
}

> {%

  // Assert status code
  client.test('When meaning is empty, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body.Translations[0]["Language"] === "ru");
    client.assert(response.body.Translations[0]["Translation"] !== "");
    client.assert(response.body.Translations[1]["Language"] === "en");
    client.assert(response.body.Translations[1]["Translation"] !== "");
  });
%}



### BadRequest - SourceLanguage is null

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "HeadWord": "såsom",
  "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
  "PartOfSpeech": "konjunktion",
  "SourceLanguage": "",
  "DestinationLanguages": [
    "en",
    "ru"
  ]
}

> {%

  // Assert status code
  client.test('When SourceLanguage is null, we expect to get an error', () => {
    client.assert(response.status === 400, "Response status is BadRequest");
  });
%}



### BadRequest - HeadWord is null

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "HeadWord": "",
  "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
  "PartOfSpeech": "konjunktion",
  "SourceLanguage": "Danish",
  "DestinationLanguages": [
    "en",
    "ru"
  ]
}

> {%

  // Assert status code
  client.test('When HeadWord is null, we expect to get an error', () => {
    client.assert(response.status === 400, "Response status is BadRequest");
  });
%}



### BadRequest - DestinationLanguages has too many elements

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "Word": "såsom",
  "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
  "PartOfSpeech": "konjunktion",
  "SourceLanguage": "Danish",
  "DestinationLanguages": [
    "en",
    "ru",
    "es"
  ]
}

> {%

  // Assert status code
  client.test('When DestinationLanguages has too many elements, we expect to get an error', () => {
    client.assert(response.status === 400, "Response status is BadRequest");
  });
%}



### Test connection to Azure Translator Service

https://api.cognitive.microsofttranslator.com/languages?api-version=3.0

###
