#@service=azure
@service=openai

### Translate from Danish to English + Russian

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "Word": "såsom",
  "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
  "PartOfSpeech": "konjunktion",
  "SourceLanguage": "da",
  "DestinationLanguages": [
    "ru",
    "en"
  ]
}

> {%

  // Assert status code
  client.test('When sending a word for translation, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body[0]["Language"] === "ru");
    client.assert(response.body[0]["Translation"] !== "");
    client.assert(response.body[1]["Language"] === "en");
    client.assert(response.body[1]["Translation"] === "such as");
  });
%}



### Translate from Danish to English + Russian, where meaning is empty

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "Word": "såsom",
  "Meaning": "",
  "PartOfSpeech": "konjunktion",
  "SourceLanguage": "da",
  "DestinationLanguages": [
    "ru",
    "en"
  ]
}

> {%

  // Assert status code
  client.test('When meaning is empty, we expect to get json back', () => {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body[0]["Language"] === "ru");
    client.assert(response.body[0]["Translation"] !== "");
    client.assert(response.body[1]["Language"] === "en");
    client.assert(response.body[1]["Translation"] === "such as");
  });
%}



### BadRequest - SourceLanguage is null

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "HeadWord": "såsom",
  "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
  "PartOfSpeech": "konjunktion",
  "SourceLanguage": "",
  "DestinationLanguages": [
    "en",
    "ru"
  ]
}

> {%

  // Assert status code
  client.test('When SourceLanguage is null, we expect to get an error', () => {
    client.assert(response.status === 500, "Response status is not 500");
  });
%}



### BadRequest - HeadWord is null

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "HeadWord": "",
  "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
  "PartOfSpeech": "konjunktion",
  "SourceLanguage": "Danish",
  "DestinationLanguages": [
    "en",
    "ru"
  ]
}

> {%

  // Assert status code
  client.test('When HeadWord is null, we expect to get an error', () => {
    client.assert(response.status === 500, "Response status is not 500");
  });
%}



### BadRequest - DestinationLanguages has too many elements

POST {{HostAddress}}/api/Translate?code={{code}}&service={{service}}
Content-Type: application/json

{
  "Word": "såsom",
  "Meaning": "bruges til angivelse af et eller flere eksempler på noget",
  "PartOfSpeech": "konjunktion",
  "SourceLanguage": "Danish",
  "DestinationLanguages": [
    "en",
    "ru",
    "es"
  ]
}

> {%

  // Assert status code
  client.test('When DestinationLanguages has too many elements, we expect to get an error', () => {
    client.assert(response.status === 500, "Response status is not 500");
  });
%}



### Test connection to Azure Translator Service

https://api.cognitive.microsofttranslator.com/languages?api-version=3.0

###
